# Generated by Django 4.1.4 on 2022-12-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=600)),
                ('site', models.CharField(choices=[('ANIQ', 'Aniq'), ('BBC', 'Bbc'), ('BUGUN', 'Bugun'), ('CHAMPIONAT', 'Championat'), ('DARYO', 'Daryo'), ('GAZETA', 'Gazeta'), ('GOAL24', 'Goal24'), ('KUN', 'Kun'), ('OLAMSPORT', 'Olamsport'), ('QALAMPIR', 'Qalampir'), ('SPORTS', 'Sports'), ('SPUTNIKNEWS', 'Sputniknews'), ('STADION', 'Stadion'), ('UZA', 'Uza'), ('ZAMIN', 'Zamin')], max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
